// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  return $("#landingPage").Chevron("render", {
    name: "Slim Shay"
  }, function(result) {
    $('body').append(result);
    return $("input[name='email_input']").on('input', function() {
      return console.log('heresa');
    });
  });
});
