// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  $(".landingPage").Chevron("render", {
    name: "Slim Shay"
  }, (function(_this) {
    return function(result) {
      $('body').append(result);
      $("#email_button").on('click', function() {
        var email;
        email = $("input[name='email_input']").val();
        $('.landing-wrapper').remove();
        return $('body').append("<div class='signed-up'> You'll here from us soon! </div>");
      });
      return $("input[name='email_input']").on('input', function() {
        return console.log('heresa');
      });
    };
  })(this));
  return 0;
});
