// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  return $(".landingPage").Chevron("render", {
    name: "Slim Shay"
  }, (function(_this) {
    return function(result) {
      $('body').append(result);
      return $("#email_button").on('click', function() {
        var email;
        email = $("input[name='email_input']").val();
        $('.landing-wrapper').remove();
        $.post("/insertEmail", {
          email: email
        }, function(data) {
          if (data.status === "success") {
            return console.log("success");
          } else {
            return console.log("failure");
          }
        });
        return $('body').append("<div class='signed-up'> You'll here from us soon! </div>");
      });
    };
  })(this));
});
